version: "2.1"

services:
  app:
    image: kimerran/help-web
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - web
    expose:
      - "80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:help.covid19ph.net"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
networks:
  web:
    external: true
